// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqO91kvw-9AS43iVd2pPSZAzTmb3rLSbE',
    appId: '1:242638941581:web:4060d127c4aad277c9e1c4',
    messagingSenderId: '242638941581',
    projectId: 'edunova-3626d',
    authDomain: 'edunova-3626d.firebaseapp.com',
    storageBucket: 'edunova-3626d.firebasestorage.app',
    measurementId: 'G-WZF9VMMG0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdeguVNUQTMZli6-6QA35AumeBoEJNQ90',
    appId: '1:242638941581:android:5244945329d0b887c9e1c4',
    messagingSenderId: '242638941581',
    projectId: 'edunova-3626d',
    storageBucket: 'edunova-3626d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqNKyKD8KixiVF4GzIRZAwb0bP_lzXqU',
    appId: '1:242638941581:ios:a387b0828f2c536dc9e1c4',
    messagingSenderId: '242638941581',
    projectId: 'edunova-3626d',
    storageBucket: 'edunova-3626d.firebasestorage.app',
    iosBundleId: 'com.example.edunovaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEqNKyKD8KixiVF4GzIRZAwb0bP_lzXqU',
    appId: '1:242638941581:ios:a387b0828f2c536dc9e1c4',
    messagingSenderId: '242638941581',
    projectId: 'edunova-3626d',
    storageBucket: 'edunova-3626d.firebasestorage.app',
    iosBundleId: 'com.example.edunovaApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqO91kvw-9AS43iVd2pPSZAzTmb3rLSbE',
    appId: '1:242638941581:web:12a050fb303d81a0c9e1c4',
    messagingSenderId: '242638941581',
    projectId: 'edunova-3626d',
    authDomain: 'edunova-3626d.firebaseapp.com',
    storageBucket: 'edunova-3626d.firebasestorage.app',
    measurementId: 'G-12H55DX4TX',
  );
}
